Improve API
FabricMC/access-widener pull request #15
Opened 2021-10-04 02:45 UTC by CoolMineman

Allows writing to a writer
Adds the aw version to the visitor
Adds a writer constructor that reads the version from the visitor

2021-10-08 23:34 UTC, Ueaj-Kerman approved these changes

2021-10-08 23:46 UTC, modmuss50 requested changes
I can see some possible benfit in using a writer, but what we have should cover most if not all use cases already?

The version should not be in the vistor.

2021-10-08 23:46 UTC, modmuss50 commented on src/main/java/net/fabricmc/accesswidener/AccessWidenerVisitor.java
> +	}
No, the version shouldnt be passed around here, the version only relates to the format and thus the reader/writer. This has already discussed in great detail on some of the recent PRs that made up 2.0

2021-10-09 00:25 UTC, CoolMineman commented
> I can see some possible benfit in using a writer, but what we have should cover most if not all use cases already?

A writer makes it nicer because instead of writing to an array then wrapping that array in a byte output stream and writing it you can just write it directly. 

> The version should not be in the vistor.

Would you prefer to expose a readBody or similar that takes in a header and a static readHeader instead? Right now it is hard to use the reader as you need to know the version to create the writer and reading the version advances the bufferedreader.

2022-05-04 02:07 UTC, closed without merging